languageCode = "en-us"
baseurl = "https://gohugo.io/"
title = "Hugo Tailwind Nord Theme"

author = "Law Zava"
description = "Law Zava's site"

pygmentsCodefences = true
pygmentsStyle = "rrt"
DefaultContentLanguage = "en"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    favicon = "favicon.svg"
    disclaimer = "No Trackers. No Cookies. No Visit Logs."
    copyright = "Copyright © 2021, Law Zava, all rights reserved."
    images = ["img/lawzava.png"]
    author = "Law Zava"
    github = "https://github.com/lawzava"
    ogimage = "/img/lawzava.png"
    sitename = "Law Zava"
    description = "Law Zava's personal site"

[languages]
    [languages.en]
        languageName = "English"
        languageCode = "en-us"
        weight = 1

[menu]
    [[menu.main]]
        identifier = "product"
        name = "Product"
        title = "Product"
        url = "#product"
        weight = 1
    [[menu.main]]
        identifier = "features"
        name = "Features"
        title = "Features"
        url = "#features"
        weight = 2
    [[menu.main]]
        identifier = "testimonials"
        name = "Testimonials"
        title = "Testimonials"
        url = "#testimonials"
        weight = 3
    [[menu.main]]
        identifier = "team"
        name = "Team"
        title = "Team"
        url = "#team"
        weight = 4
    [[menu.main]]
        identifier = "contact"
        name = "Contact"
        title = "Contact"
        url = "#contact"
        weight = 5

